# Generated by Django 5.1.4 on 2025-03-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('variety', models.CharField(db_index=True, max_length=100)),
                ('price', models.FloatField()),
                ('area', models.CharField(max_length=100)),
                ('unit', models.CharField(default='元/公斤', max_length=20)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['variety', '-data'],
                'indexes': [models.Index(fields=['variety', 'data'], name='nongapp_pro_variety_e13553_idx')],
            },
        ),
    ]
